name: Docker Image CI

on: [push]

jobs:

  build_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build, Tag, Publish Docker
      uses: HurricanKai/Publish-Docker-Github-Action@1.12.1
      with:
        name: jasonkolodziej/twit_st
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./st_sentiment_app/Dockerfile
  build_ml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build, Tag, Publish Docker
      uses: HurricanKai/Publish-Docker-Github-Action@1.12.1
      with:
        name: jasonkolodziej/twit_stml
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./st_ml/Dockerfile
